version: '{build}'
clone_depth: 3 
image:
  - Visual Studio 2019
environment:
  matrix:
    - job_name: java11-linux-site
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/
      SITE: 1
    - job_name: java8-win-x64
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - job_name: java8-win-x64
      JAVA_HOME: C:\Program Files\Java\jdk11
    - job_name: java8-win-x64
      JAVA_HOME: C:\Program Files\Java\jdk17
    - job_name: java8-win-x64
      JAVA_HOME: C:\Program Files\Java\jdk21  
    - job_name: java8-linux-deploy
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/
      DEPLOY: 1
matrix:
  fast_finish: true
init:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - sh: export PATH="$JAVA_HOME/bin:$PATH"	  
build_script:
  - mvn install --settings .ci-settings.xml -DskipTests=true -U -B
test_script:
  - mvn test -Dassembly.skipAssembly=true -B 
  - bash -c "if [ ${SITE} ]; then mvn site -B; fi"
deploy_script:
  - bash -c "if [ ${DEPLOY} ] && [ ${APPVEYOR_REPO_BRANCH} = 'main' ]; then mvn deploy --settings .ci-settings.xml -DskipTests=true -B; fi"   
cache:
  - '%USERPROFILE%\.m2'
  - '$HOME/.m2'